### ISSUE TITLE
Segfaults on Mojave 10.14

### ISSUE THREAD

**Issue by LKay** [ankane/pgsync#69] opened 2019-12-25 02:18 UTC
Might be related to #67. When running pgsync it always fails with segmentation fault in:

```
/Users/user/.rbenv/versions/2.6.0/lib/ruby/gems/2.6.0/gems/parallel-1.13.0/lib/parallel.rb:74:in `rescue in work': Parallel::DeadWorker (Parallel::DeadWorker)
```

Is there any fix for this?

**Comment by ankane** [comment] 2019-12-27 00:21
Hey @LKay, thanks for reporting. Unfortunately, I'm not sure how to reproduce. I'd try uninstalling all of pgsync's dependencies and reinstalling it. https://github.com/ankane/pgsync/blob/dd8f17726c00a300987baaf968a5081daefea2f7/pgsync.gemspec#L21-L24

**Comment by LKay** [comment] 2019-12-27 00:55
I tried that, but unfortunately without success. I also tried to upgrade ruby on my machine, but didn't have much effect either. Might be some kind or architecture mismatch in some of the dependencies. I'll upgrade my OS to the newer version and see if that helps. Currently as a workaround I dockerized pgsync and run it as docker container (no issues with `linux-amd64` architecture, though).

**Comment by ankane** [comment] 2020-01-08 01:04
Hey @LKay, I'm now seeing this error on my machine. It's appears to be due to this issue: https://github.com/ged/ruby-pg/issues/311

I was able to solve it by adding `?gssencmode=disable` to the end of the `to` and `from` urls in `.pgsync.yml`.

Or you can disable parallel syncing with:

```ruby
pgsync --debug
```

**Comment by thbar** [comment] 2020-01-14 10:40
FWIW, you can have a more global effect by starting the process with `PGGSSENCMODE="disable"`, if needed (see https://github.com/ged/ruby-pg/issues/311#issuecomment-561927000).

**Comment by ankane** [comment] 2020-01-21 01:18
Reinstalling PostgreSQL from Homebrew fixed it for me, thanks to this PR: https://github.com/Homebrew/homebrew-core/pull/47494

**Comment by DumasOlivier** [comment] 2020-01-21 15:27
Reinstall PostgreSQL from Hombrew fixed the problem for me :)
Thanks Andrew

**Comment by ankane** [comment] 2020-01-21 19:21
Great, will close this out.

**Closed by ankane** 2020-01-21 19:21 UTC
